torchrun \
    --standalone \
    --nproc_per_node=4 \
    run.py \
    --task_name ssl \
    --model VQ_BERT \
    --learning_rate 1e-3 \
    --normalize \
    --patience 0 \
    --num_epochs 120 \
    --mask_length 10 \
    --mask_ratio 0.2 \
    --codebook_num 4 \
    --num_embedding 1024 \
    --kernel_size 5 \
    --attn_head 8 \
    --e_layers 4 \
    --d_hidden 64 \
    --d_model 128 \
    --train_batch_size 64 \
    --test_batch_size 64