torchrun \
    --standalone \
    --nproc_per_node=4 \
    run.py \
    --task_name anomaly_detection \
    --model SimMTM \
    --learning_rate 1e-3 \
    --normalize \
    --patience 0 \
    --num_epochs 60 \
    --e_layers 2 \
    --d_model 256 \
    --activation "gelu" \
    --linear_dropout 0.6 \
    --train_batch_size 64 \
    --test_batch_size 64 \
    --input_len 60 \
    --output_len 60 \
    --mask_ratio 0.15 \
    --positive_num 2 \
    --temperature 0.1 \
    --attn_head 8 \
    --dropout 0.3 \
    --num_workers 8 \
    --use_scheduler \
    --weight_decay 1e-3 \
    --pretrained_path "/home/guihaokun/Time-Series-Pretrain/logging/ssl/SimMTM/SimMTM_240126_0019/checkpoint/last.pth.tar" \
    --balance \
    --input_len 12 \
    --dataset TUAB \
    --root_path "/data/guihaokun/resample/tuh_eeg_abnormal/" \
    --log_dir "/home/guihaokun/Time-Series-Pretrain/logging_ab" 
    