torchrun \
    --standalone \
    --nproc_per_node=2 \
    run.py \
    --task_name anomaly_detection \
    --model VQ_BERT \
    --learning_rate 5e-5 \
    --normalize \
    --patience 0 \
    --num_epochs 60 \
    --codebook_num 4 \
    --codebook_item 1024 \
    --kernel_size 5 \
    --attn_head 8 \
    --e_layers 4 \
    --d_hidden 128 \
    --d_model 512 \
    --train_batch_size 64 \
    --test_batch_size 64 \
    --dropout 0.3 \
    --min_space 1 \
    --mask_dropout 0.0 \
    --enc_type "rel" \
    --balanced \
    --use_scheduler \
    --num_workers 16 \
    --pretrained_path "/home/guihaokun/Time-Series-Pretrain/logging/ssl/VQ_BERT/VQ_BERT_231102_020307/checkpoint/last.pth.tar"