torchrun \
    --standalone \
    --nproc_per_node=4 \
    run.py \
    --task_name classification \
    --model DCRNN \
    --graph_type distance \
    --normalize \
    --use_fft \
    --learning_rate 1e-3 \
    --train_batch_size 64 \
    --test_batch_size 64 \
    --data_augment \
    --patience 0 \
    --pretrained_path "/home/guihaokun/Time-Series-Pretrain/logging/ssl/DCRNN/DCRNN_240111_112811/checkpoint/last.pth.tar"\
    --dropout 0.2 \
    --balanced \
    --use_scheduler \
    --weight_decay 1e-4 \
    --num_workers 10 \
    --num_epochs 60